---
output: github_document
editor_options: 
  markdown: 
    wrap: sentence
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ANOVA

The goal of ANOVA is to help researchers analyse their experimental data easily for variance and also carry out post hoc test without learning much code.
The interface is easy to use and straightforward.

## Access

You can access the app from [ANOVA](https://blessing-oladoja.shinyapps.io/ANOVA/)

## Analysis of Variance

Using the App, it is possible to carry analysis of variance for;

-   Completely randomized design.

-   Randomised complete block design.

-   Latin square design.

## Post Hoc Analysis

The available post hoc analysis are;

-   Least significant difference test.

-   Tukey's Honestly significant difference test.

-   Duncan multiple range test.

## Tables and Plots

It is also possible to download the results of the analysis as csv and jpeg files.

## Procedures

To use the app, the user have to import their data which is already in a tidy format (long format) and select the appropriate columns, then click on `apply changes`
